---
site_name: "path-embedding"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  
#watch:
#  - src/path_embedding/schema

nav:
  - Home: index.md
  
exclude_docs: |
  /templates-linkml/

site_url: https://justaddcoffee.github.io/path-embedding
repo_url: https://github.com/justaddcoffee/path-embedding
